name: swatmf_test3
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=2.0
  - numpy>=1.25 
  - matplotlib 
  - jupyter 
  - pip
  - notebook 
  - scipy 
  - shapely
  - rtree
  - pyproj>=2.0
  - pyshp
  - psutil
  - git
  - nbconvert
  - pip:
    - -e ./dependencies/swatmf
    - -e ./dependencies/flopy
    - -e ./dependencies/pyemu
    # - flopy
    # - git+https://github.com/modflowpy/flopy.git
    # - pyemu
    # - git+https://github.com/pypest/pyemu.git@develop
    - hydroeval
    - termcolor
    - tqdm
